services:
  web:
    build: ./fe
    ports:
      - "5002:5002"
    depends_on:
      - backend-service
    networks:
      - app-network

  backend-service:
    build: ./be
    ports:
      - "5001:5001"
    depends_on:
      - mysqldb
    networks:
      - app-network

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crypto_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge